### ISSUE TITLE
Ticket N°38819 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Alco-Stock#1]
Al crear un comodato desde Gestión Comodatos ---> agregar y buscar por nro de serie un bien Cel para asociar no trae el bien que corresponde a ese nro de serie. 
Caso ejemplo: nro serie 100 corresponde a una cámara web, pero trae una impresora zebra con nro de serie 12J125100565

Trabar en Versión: 1.6

**Comment by rominariquelme** [comment]
Se modificaron los criterios de filtros para Agregar Comodato de Gestion Comodato
