### ISSUE TITLE
Subir a Testing

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Alco-Stock#2]
Lea, necesito subir los cambios subidos a la versión 1.6 de Alco Stock a testing.

**Comment by leoimoli** [comment]
Lea, necesito subir los cambios subidos a la versión 1.7 de Alco Stock a testing.

**Comment by leodimonio** [comment]
listo 
https://testing01.seguridadvial.gov.ar/AlcoStock/login.aspx?ReturnUrl=%2fAlcoStock

**Comment by leoimoli** [comment]
Se informo del pase a la gente del Dpto de análisis.
