### ISSUE TITLE
Restructuración ALCO

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Alco-Stock#3]
Estimados, como ya saben o se están enterando debemos realizar una restructuración del sistema actual de Alco Stock. Adjunto les paso la documentación que recibimos para que la vayan viendo y dsp nos juntamos para definir como encaramos la primer etapa.
[AlcoStock documento tecnico.docx](https://github.com/leoimoli/Alco-Stock/files/330091/AlcoStock.documento.tecnico.docx)
[ERS_AlcoStock_cyn_enconstruccion.docx](https://github.com/leoimoli/Alco-Stock/files/330092/ERS_AlcoStock_cyn_enconstruccion.docx)

**Comment by EliasWasinger** [comment]
Tomá, te regalo la E que te comiste en reestructuración. 
Para cuándo vamos a tener un poco más de info de lo que hay que hacer y sobre cuándo empezamos
