### ISSUE TITLE
Pasaje a Produccion

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Alco-Stock#5]
Generar Deploy de Alco Stock Versión 1.6

**Comment by leodimonio** [comment]
listo te paso la url del repo donde esta el precompilado
https://repo.ansv.gov.ar:8443/svn/ANSV/trunk/General/Fuentes/AlcoStock-Versiones/Deploys/V-1.6.2

**Comment by leoimoli** [comment]
Versión de Testing(#2)

**Comment by leoimoli** [comment]
El día 07/07/2016 se subió a Testing la versión de Alco Stock.
